OPTIONS (SKIP=1)
LOAD DATA 
CHARACTERSET UTF8
INFILE 'Book_1.csv'
BADFILE 'my_bad_file.bad'
APPEND
INTO TABLE TEACHER_LOAD
FIELDS TERMINATED BY ';'
TRAILING NULLCOLS
(
    TEACHER        "UPPER(:TEACHER)" ,
    TEACHER_NAME  "UPPER(:TEACHER_NAME)",
    SALARY        decimal EXTERNAL "ROUND(:SALARY, 2)",
    BIRHTDAY      DATE "dd.mm.yyyy" 
)